// Generated by CoffeeScript 1.7.1
(function() {
  define(["jquery", "js/app/model", "js/app/responsiveViewFactory"], function(jq, Model, ResponsiveViewFactory) {
    var BarnDoorController;
    BarnDoorController = (function() {
      function BarnDoorController(targetDivName) {
        this.targetDivName = targetDivName;
      }

      BarnDoorController.prototype.setup = function(configuration) {
        this.configuration = configuration;
        console.log("setup with view factory...");
        this.appModel = Model.buildModelFromConfigurationObject(this.configuration);
        this.viewFactory = new ResponsiveViewFactory();
        $(document).bind('screenSizeChanged', ((function(_this) {
          return function(evt, data) {
            return _this.swapInView();
          };
        })(this)));
        this.swapInView();
        return setTimeout(((function(_this) {
          return function() {
            return _this.continueSlideshow();
          };
        })(this)), this.configuration.timeBetweenSlides);
      };

      BarnDoorController.prototype.swapInView = function() {
        var _ref;
        if (this.view != null) {
          this.view.pseudoDestructor();
          this.view = null;
        }
        this.view = this.viewFactory.constructActiveView(this.targetDivName, this.appModel.imageWidth, this.appModel.imageHeight);
        return (_ref = this.view) != null ? _ref.renderInitialView(this.appModel.getActivePair()) : void 0;
      };

      BarnDoorController.prototype.continueSlideshow = function() {
        var _ref;
        this.appModel.advanceToNextPair();
        if ((_ref = this.view) != null) {
          _ref.showNextPair(this.appModel.getActivePair());
        }
        return setTimeout(((function(_this) {
          return function() {
            return _this.continueSlideshow();
          };
        })(this)), this.configuration.timeBetweenSlides);
      };

      return BarnDoorController;

    })();
    return BarnDoorController;
  });

}).call(this);
