// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["jquery", "js/app/abstractview"], function(jq, AbstractView) {
    var SimpleView;
    SimpleView = (function(_super) {
      __extends(SimpleView, _super);

      function SimpleView(targetDivName, imgWidth, imgHeight) {
        var detailStyle, details, header, headerStyle, img, imgStyle, side, slideContainer, slideStyle, someWidth, _i, _len, _ref;
        this.targetDivName = targetDivName;
        this.imgWidth = imgWidth;
        this.imgHeight = imgHeight;
        this.$ = jq;
        this.targetDiv = $("#" + this.targetDivName);
        console.log("constructing simple view!");
        someWidth = "200px";
        _ref = ["left", "right"];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          side = _ref[_i];
          slideContainer = $("<div/>").attr("id", "slide" + side + "Container").appendTo(this.targetDiv);
          img = $("<img/>").attr("id", "img" + side + "Container").appendTo(slideContainer);
          header = $("<div/>").attr("id", "label" + side + "Container").appendTo(slideContainer);
          details = $("<div/>").attr("id", "desc" + side + "Container").appendTo(slideContainer);
          slideStyle = {
            float: "left",
            "padding": "10px"
          };
          imgStyle = {
            width: someWidth
          };
          headerStyle = {
            font: "20px Helvetica",
            width: someWidth,
            height: "50px",
            "background-color": "gray"
          };
          detailStyle = {
            width: someWidth,
            height: "100px",
            "background-color": "yellow"
          };
          slideContainer.css(slideStyle);
          img.css(imgStyle);
          header.css(headerStyle);
          details.css(detailStyle);
        }
      }

      SimpleView.prototype.renderInitialView = function(pair) {
        return this.showNextPair(pair);
      };

      SimpleView.prototype.showNextPair = function(pair) {
        this.leftSlide = pair.leftSlide;
        this.rightSlide = pair.rightSlide;
        console.log("SHOWING [" + this.leftSlide.title + "]/[" + this.rightSlide.title + "]");
        $("#imgleftContainer").attr("src", this.leftSlide.imgUrl);
        $("#imgrightContainer").attr("src", this.rightSlide.imgUrl);
        $("#labelleftContainer").html(this.leftSlide.title);
        $("#labelrightContainer").html(this.rightSlide.title);
        $("#descleftContainer").html(this.leftSlide.details);
        return $("#descrightContainer").html(this.rightSlide.details);
      };

      SimpleView.prototype.pseudoDestructor = function() {
        console.log("cleaning up custom simple...");
        $("#" + this.targetDivName + " > div").remove();
        return SimpleView.__super__.pseudoDestructor.apply(this, arguments);
      };

      return SimpleView;

    })(AbstractView);
    return SimpleView;
  });

}).call(this);

//# sourceMappingURL=simpleview.map
