// Generated by CoffeeScript 1.7.1
(function() {
  define([], function() {
    var Slide;
    Slide = (function() {
      Slide.SIDES = {
        LEFT: "left",
        RIGHT: "right"
      };

      function Slide(side, imgUrl, title, details, fontColor) {
        this.side = side;
        this.imgUrl = imgUrl;
        this.title = title;
        this.details = details;
        this.fontColor = fontColor;
      }

      Slide.prototype.toString = function() {
        return "{side=" + this.side + ", url=" + this.imgUrl + ", title='" + this.title + "'}";
      };

      return Slide;

    })();
    return Slide;
  });

}).call(this);
