// Generated by CoffeeScript 1.7.1
(function() {
  define([], function() {
    var SlidePair;
    SlidePair = (function() {
      function SlidePair(leftSlide, rightSlide) {
        this.leftSlide = leftSlide;
        this.rightSlide = rightSlide;
      }

      SlidePair.prototype.toString = function() {
        return "\n\t" + this.leftSlide + "\n\t" + this.rightSlide;
      };

      return SlidePair;

    })();
    return SlidePair;
  });

}).call(this);
